#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2025 Edgecast Cloud LLC.

if [[ $1 == -P ]]; then
cat << EOF
TIME                 UUID
Aug 20 18:06:38 8c20097b-fc6b-c4a7-f868-b89d5aa567a8

hc://:server-id=headnode/motherboard=0/chip=0/core=0?sensor=temp
  group: facility                       version: 1   stability: Private/Private
    reading           double    64.000000

hc://:server-id=headnode/motherboard=0/chip=0/core=1?sensor=temp
  group: facility                       version: 1   stability: Private/Private
    reading           double    72.000000

hc://:server-id=headnode/motherboard=0/chip=0?sensor=temp
  group: facility                       version: 1   stability: Private/Private
    reading           double    72.000000

hc://:server-id=headnode/motherboard=0/chipset=0?sensor=temp
  group: facility                       version: 1   stability: Private/Private
    reading           double    72.000000
EOF
exit
fi
