#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2020 Joyent, Inc.

if [[ $1 == -P ]]; then
cat << EOF
TIME                 UUID
Aug 20 18:06:38 8c20097b-fc6b-c4a7-f868-b89d5aa567a8

hc://:server-id=headnode/motherboard=0/chip=0/core=0?sensor=temp
  group: facility                       version: 1   stability: Private/Private
    reading           double    64.000000

EOF
exit
fi

cat << EOF
TIME                 UUID
Aug 20 18:03:17 e7b8d2a7-c534-cd42-e8f3-cbb41ba642f5

hc://:server-id=headnode/motherboard=0/chip=0/core=0?sensor=temp

hc://:server-id=headnode/motherboard=0/chip=0/core=1?sensor=temp

hc://:server-id=headnode/motherboard=0/chip=0?sensor=temp

hc://:server-id=headnode/motherboard=0/chipset=0?sensor=temp

EOF
