#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2020 Joyent, Inc.

cat << EOF
configured        configured
failed            installed
incomplete        incomplete
running           running
shutting_down     shutting_down
stopped           installed
EOF
