#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2025 Edgecast Cloud LLC.
#
case "$1" in
    list)
        printf "3166513653031\t2398521400025\t0\n"
    ;;
    *)
        exit 0;;
esac
