#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2025 Edgecast Cloud LLC.

case "$1 $2" in
    "list -Hpo")
        # zones_dataset.prom
        if [[ "$5" == "zones" ]]; then
            printf "5314993440578\t250041612478\t0\n"
        fi
    ;;
    *)
        exit 0;;
esac