#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2025 Edgecast Cloud LLC.

set -o pipefail

# Colors - use always to force output through make
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

PLUGIN="$1"
ZONE_UUID="$2"

OUTPUT=$($PLUGIN $ZONE_UUID)

# Determine output directory based on plugin path
if [[ "$PLUGIN" == gz-plugins/* ]]; then
    EXPECTED_OUTPUT_FILE=tests/outputs/gz-plugins/$(basename $PLUGIN)
elif [[ "$PLUGIN" == vm-plugins/* ]]; then
    EXPECTED_OUTPUT_FILE=tests/outputs/vm-plugins/$(basename $PLUGIN)
else
    echo -e "${RED}[ERROR]: Unknown plugin directory for $PLUGIN"
    exit 1
fi

echo -e "${YELLOW}[INFO] testing $PLUGIN with zone UUID: $ZONE_UUID...${NC}"


echo -e "${YELLOW}[INFO] testing output length for $PLUGIN...${NC}"
if [[ -z "$OUTPUT" ]]; then
  echo -e "${RED}[FAILED]: plugin returned no output $PLUGIN.${NC}"
  exit 1
fi

echo -e "${YELLOW}[INFO] testing expected and actual output for $PLUGIN...${NC}"
if [[ -f "$EXPECTED_OUTPUT_FILE" ]]; then
  diff --color=always -u $EXPECTED_OUTPUT_FILE <(cat<<<"$OUTPUT")
  if [[ "$?" != "0" ]]; then
    echo -e "${RED}[FAILED]: expected output and actual output do not match for $PLUGIN.${NC}"
    exit 1
  fi
else
  echo -e "${YELLOW}[WARNING] no expected output file found for $PLUGIN...${NC}"
fi
cat<<<"$OUTPUT" | promtool check metrics
if [[ "$?" != "0" ]]; then
  echo -e "${RED}[FAILED]: plugin output is not valid prometheus format $PLUGIN.${NC}"
  exit 1
fi
echo -e "${GREEN}[PASSED]: $PLUGIN${NC}"
