#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2025 Edgecast Cloud LLC.

set -o pipefail

# Colors - use always to force output through make
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

for i in "$@"; do
    OUTPUT=$($i)
    echo -e "${YELLOW}[INFO] validating $i..."
    diff --color=always -u tests/outputs/$(basename $i) <(cat<<<"$OUTPUT")
    if [[ "$?" != "0" ]]; then
      echo -e "${RED}[FAILED]: expected output and actual output do not match for $i."
      exit 1
    fi
    cat<<<"$OUTPUT" | promtool check metrics
    if [[ "$?" != "0" ]]; then
      echo -e "${RED}[FAILED]: plugin output is not valid prometheus format $i."
      exit 1
    fi
    echo -e "${GREEN}[PASSED]: $i"
done
